name: 'Notion To Github Blog'
description: 'Convert notion page to markdown for github blog'
author: 'Troubleskiller <troubleskiller@outlook.com>'
branding:
  icon: 'edit-3'
  color: 'blue'
inputs:
  notion_token:
    description: 'Notion Token'
    required: true
  notion_database_id:
    description: 'Notion Database ID'
    required: true
  md_store_path_prefix:
    description: 'the dir where the markdown will save in, Default: content/posts'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
